# -*- coding: utf-8 -*-
"""archivo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15Hm7IpljDrCsBwYx3ue2-ZLYOiosRkUo
"""

print("Hola")